apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  labels:
    argocd.argoproj.io/instance: spring-petclinic-service
    app: spring-petclinic
  name: spring-petclinic_eso
  namespace: backend-services
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: spring-petclinic_db
      property: dbUser
    secretKey: DB_USERNAME
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: spring-petclinic_db
      property: dbPass
    secretKey: DB_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: backend-services-secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: spring-petclinic-secrets