apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: spring-petclinic
  name: spring-petclinic-alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    external-dns.alpha.kubernetes.io/hostname: spring-petclinic.blnk.us
spec:
  ingressClassName: alb
  rules:
    - host: spring-petclinic.blnk.us
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: spring-petclinic-service
              port:
                number: 80
