apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::203360591048:role/spring-petclinic-eso
  name: external-secrets-sa
  namespace:  spring-petclinic